version: '3.3'

services:
  db-server:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - db_data
      - ./mysql/init:/docker-entrypoint-initdb.d
    depends_on:
      - db_data
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root

  app:
    image: golang:1.10.3
    working_dir: /go/src/github.com/GITHUB_NAME/REPOSITORY_NAME
    ports:
      - 8080:8080
    volumes:
      - ./vendor:/go/src/github.com
      - ./:/go/src/github.com/GITHUB_NAME/REPOSITORY_NAME
    depends_on:
      - db-server
    command: ["./wait-for-it.sh", "db-server:3306", "--timeout=200", "--", "go", "run", "/go/src/github.com/GITHUB_NAME/REPOSITORY_NAME/cmd/app.go"]

  db_data:
    image: busybox
    volumes:
      - /var/lib/mysql
      - /var/log/mysql
